# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install:
  - gem install xcpretty
script:
  - xcodebuild test -sdk iphonesimulator -workspace DateClay.xcworkspace -scheme DateClay -configuration Debug OBJROOT=build ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty